# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e68a67b664574e1db6aa5fec0fe25af269c72587d93c1307ef40a44fe8355e3e2a1186c610aebf80aaac766cb94aa59c127cab2ccc850597f4861f3c1252711

test:
  secret_key_base: ec12c10ecaa98f9dfd1d5eafeedffe973fd0ba5f083aaaa3a54690b39386cd83d484338083fe9238af520a9e55295e6631c07cf46481e15b7215383e7aee1a1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
